title:              Flavio Akira Portfolio
email:              fla_akira@hotmail.com
description:        Portfolio
author:             Flavio Akira Tikaishi Oliveira
baseurl:            ""
url:                "https://flaakira.github.io"

# Social Profiles
twitter_username:   
github_username:    https://github.com/flaakira
facebook_username:  https://www.facebook.com/flavioakira.tikaishi
instagram_username:  https://www.instagram.com/flaakira/
linkedin_username: https://www.linkedin.com/in/flavio-akira/?locale=en_US

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
